import { Card, CardContent } from "@/components/ui/card";

/**
 * /methodology — public honesty page. Documents every data source and the exact
 * risk threshold bands before they ship (Scientific Grounding requirement #3 + risk
 * constraint #3). Keep in sync with docs/architecture/SCIENTIFIC_GROUNDING.md and
 * grounded_model.py threshold constants.
 */
export default function Methodology() {
  return (
    <div className="min-h-screen w-full bg-gray-50 py-10 px-4">
      <div className="mx-auto max-w-3xl space-y-6">
        <header className="space-y-2">
          <a href="/" className="text-sm text-blue-600 hover:underline">← Back to the map</a>
          <h1 className="text-3xl font-bold text-gray-900">How fupit gets its numbers</h1>
          <p className="text-gray-600">
            Every value on this site traces to real climate science. We do not invent
            coefficients or warming rates. Where we cannot ground a number, we leave it
            blank rather than guess. This page shows the full chain.
          </p>
        </header>

        <Card className="bg-white text-gray-900">
          <CardContent className="prose prose-sm prose-slate max-w-none pt-6">
            <h2>What the forecast is built from</h2>
            <ul>
              <li>
                <strong>Temperature and precipitation change</strong> — CMIP6, the
                model ensemble behind the IPCC Sixth Assessment Report. We take the
                multi-model average change for each scenario, decade by decade to 2100.
              </li>
              <li>
                <strong>Present-day baseline</strong> — WorldClim v2.1 observed monthly
                climatology at 10 arc-minutes for 1970 to 2000 where land data is
                available, with CMIP6 historical monthly climatology as the fallback.
                Future absolute values are this baseline plus the modeled change.
              </li>
              <li>
                <strong>Sea-level rise</strong> — IPCC AR6 regional projections, per
                scenario.
              </li>
              <li>
                <strong>Heat, drought and flood risk</strong> — CMIP6 ETCCDI extreme-climate
                indices (the standard set used in the scientific literature), scored against
                published thresholds. See the table below.
              </li>
              <li>
                <strong>Climate twin</strong> — the nearest present-day city in the indexed
                catalog, found by comparing standardized monthly temperature and precipitation
                vectors generated by the same grounded engine. It is a catalog analog, not a
                claim that every local impact is identical. The public API returns the catalog
                version, compared count, distance components, and caveats with the result.
              </li>
            </ul>

            <h2>The "hot model" correction</h2>
            <p>
              Some CMIP6 models run warmer than the observational record and paleoclimate
              evidence support. The IPCC did not simply average the raw models; it adjusted
              its assessed warming toward observations. We do not hide that adjustment in
              the headline number. For temperature, the default value shown in the app is
              the raw CMIP6 model consensus; the IPCC-calibrated value, calibration factor,
              and adjustment are shown beside it. Precipitation has no comparable single
              assessed anchor, so we show it as model average plus spread, labeled as such.
              We do not fabricate a calibration we cannot ground.
            </p>

            <h2>Scenario roles, not political probability</h2>
            <p>
              The source grid carries five SSP pathways for temperature, precipitation and sea
              level context. The app offers full habitability forecasts for the four scenarios
              that also have grounded heat, drought and flood layers. SSP2-4.5 is the default
              middle-path reference because 2025 UNEP current-policy and Climate Action
              Tracker policies/action estimates put end-century warming roughly between
              2.6 C and just below 3 C, making it the closest fully grounded SSP pathway in
              this package. The default policy version is current-policy-reference-2025. It
              is a reference, not a promise, prophecy, or hidden average of scenarios.
              SSP5-8.5 remains available as a very-high-emissions stress test, not as
              "business as usual." We cite the scenario and show the raw output so readers
              can judge the pathway instead of being forced into a single narrative.
            </p>

            <h2>Risk thresholds (exact bands)</h2>
            <p>
              Each 0 to 100 risk score is a transparent rescaling of a real, cited quantity.
              The raw value and its unit are always shown alongside the score. The bands:
            </p>
            <table>
              <thead>
                <tr><th>Hazard</th><th>Real quantity (cited)</th><th>0 to 100 mapping</th></tr>
              </thead>
              <tbody>
                <tr>
                  <td>Heat</td>
                  <td>Tropical nights: nights per year with minimum above 20°C (ETCCDI TR; WHO heat-health)</td>
                  <td>Shown as the raw count per year</td>
                </tr>
                <tr>
                  <td>Drought</td>
                  <td>Longest dry spell: consecutive days under 1 mm of rain (ETCCDI CDD)</td>
                  <td>0 days → 0, 180 days (half a year) → 100, linear</td>
                </tr>
                <tr>
                  <td>Flood</td>
                  <td>Maximum 5-day rainfall total, mm (ETCCDI Rx5day; IPCC AR6 heavy-precip)</td>
                  <td>0 mm → 0, 300 mm → 100, linear</td>
                </tr>
              </tbody>
            </table>
            <p>
              Where a location has no usable model data, the score is left blank, never
              guessed. The very-low-emissions scenario (SSP1-1.9) has no matching ETCCDI
              heat/drought/flood source in this package, so full habitability forecasts with
              those risk penalties are withheld rather than interpolated.
            </p>

            <h2>Habitability score</h2>
            <p>
              The single habitability number is a weighted blend of temperature comfort
              (weight 0.45), rainfall adequacy (0.35), a fixed adaptation allowance, minus
              penalties for heat, drought and flood. It is a transparent summary, not a model
              output, and the full breakdown is shown so you can see every component.
            </p>

            <h2>Large-scale circulation context</h2>
            <p>
              For broad regions where it is relevant, the app may show an AMOC/Gulf Stream
              context note. This uses IPCC AR6 Working Group I assessment language only:
              the Atlantic Meridional Overturning Circulation is very likely to weaken
              during the 21st century, while abrupt collapse before 2100 is not the central
              IPCC assessment. fupit does not apply a local cooling correction, warming
              correction, collapse date, or deterministic local impact from AMOC context.
            </p>

            <h2>Honesty notes</h2>
            <ul>
              <li>
                The observed baseline uses WorldClim's 1970 to 2000 climatology, while
                CMIP6 deltas are referenced to 1995 to 2014. We disclose that period
                mismatch in the projection receipt instead of hiding it. The raw CMIP6
                <em> change</em> signal is the headline; the IPCC-calibrated version is
                reported as an assessed comparison value.
              </li>
              <li>
                The extreme-index dataset is marked by its providers as no longer actively
                supported and provided as is. The index definitions are the published ETCCDI
                standard; we cite it as a frozen product.
              </li>
              <li>
                Every projection carries its scenario, its source, and an uncertainty range
                from the spread across models. It also carries the source-year basis: this
                package's scenario layers start at 2030, so near-current 2025/2026 points
                disclose that they use the earliest packed scenario layer rather than a true
                historical hindcast. We never collapse that range or cadence into false
                precision.
              </li>
            </ul>

            <p className="text-gray-500">
              Sources: WorldClim v2.1 (Fick & Hijmans 2017); IPCC AR6 Working Group I;
              CMIP6 (Eyring et al. 2016); ETCCDI indices (Sillmann et al. 2013); IPCC
              AR6 sea-level projections; Climate Action Tracker thermometer; Hausfather
              &amp; Peters 2020 on high-emissions scenario framing.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
