// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/climate-single/ResultsPage.tsx": () => import("../components/mockups/climate-single/ResultsPage.tsx"),
  "./components/mockups/climate-compare/ComparisonPage.tsx": () => import("../components/mockups/climate-compare/ComparisonPage.tsx"),
  "./components/mockups/climate-comparison/ComparisonPage.tsx": () => import("../components/mockups/climate-comparison/ComparisonPage.tsx")
};