import assert from "node:assert/strict";
import fs from "node:fs";
import { loadDataQuality } from "../server/data-quality";

const report = loadDataQuality() as Record<string, any>;

assert.equal(report.version, "data-quality-v1");
assert.ok(String(report.methodVersion).startsWith("grounded-grid-i16-v2"));
assert.equal(report.sourceRegistryVersion, "source-registry-v1");
assert.ok(Array.isArray(report.artifacts) && report.artifacts.length >= 10);
assert.ok(report.artifacts.every((artifact: any) => artifact.bytes > 0 && /^[a-f0-9]{64}$/.test(artifact.sha256)));
assert.equal(report.sourceRegistry.rowCount, 11);
assert.ok(report.sourceRegistry.rows.some((row: any) => row.sourceId === "ipcc-ar6-amoc" && row.displayPolicy === "show-as-context-no-local-correction"));
assert.ok(report.sourceRegistry.rows.some((row: any) => row.sourceId === "natural-earth-populated-places-110m-v5" && row.displayPolicy === "show-with-bounded-catalog-caveat"));
assert.ok(report.sourceRegistry.rows.some((row: any) => row.sourceId === "unep-egr-2025-current-policies" && row.displayPolicy === "show-as-policy-context-no-local-correction"));
assert.ok(report.sourceRegistry.rows.some((row: any) => row.sourceId === "cat-2025-warming-projections" && row.displayPolicy === "show-as-policy-context-no-local-correction"));
assert.ok(String(report.sourceRegistry.policy).includes("No public metric"));
const cmip6Source = report.sourceRegistry.rows.find((row: any) => row.sourceId === "cmip6-scenariomip");
assert.ok(cmip6Source);
assert.ok(String(cmip6Source.license).includes("Model-specific CMIP6 terms"));
assert.ok(String(cmip6Source.method).includes("Raw model-consensus anomaly"));
assert.ok(Array.isArray(cmip6Source.variables) && cmip6Source.variables.includes("temperature anomaly"));
const etccdiSource = report.sourceRegistry.rows.find((row: any) => row.sourceId === "cmip6-etccdi");
assert.equal(etccdiSource?.commercialReuse, "restricted");
assert.equal(etccdiSource?.redistribution, "restricted");
const naturalEarthSource = report.sourceRegistry.rows.find((row: any) => row.sourceId === "natural-earth-populated-places-110m-v5");
assert.equal(naturalEarthSource?.commercialReuse, "allowed");
assert.ok(String(naturalEarthSource?.license).includes("public domain"));
assert.equal(report.defaultScenarioPolicy.scenario, "ssp245");
assert.equal(report.defaultScenarioPolicy.policyVersion, "current-policy-reference-2025");
assert.ok(report.defaultScenarioPolicy.basis.includes("UNEP current-policy"));
assert.ok(report.defaultScenarioPolicy.basis.includes("not a prediction or hidden scenario average"));
assert.deepEqual(report.defaultScenarioPolicy.sourceIds, ["unep-egr-2025-current-policies", "cat-2025-warming-projections"]);
assert.deepEqual(report.defaultScenarioPolicy.supportedFullForecastScenarios, ["ssp126", "ssp245", "ssp370", "ssp585"]);
assert.equal(report.defaultScenarioPolicy.gridHash, report.grids.primary.artifactHash);
assert.ok(String(report.defaultScenarioPolicy.gridHash).startsWith("sha256:0dc3f9d188e4d757"));
assert.equal(report.rankings.catalogCount, 2);
assert.equal(report.rankings.catalogSize, 111);
assert.equal(report.rankings.entryCount, 1632);
assert.ok(report.rankings.catalogs.some((catalog: any) => catalog.catalog === "curated_cities" && catalog.catalogSize === 45));
assert.ok(report.rankings.catalogs.some((catalog: any) => catalog.catalog === "natural_earth_populated_places_110m" && catalog.catalogSize === 66));
assert.ok(report.rankings.sourceIds.includes("natural-earth-populated-places-110m-v5"));
assert.equal(report.trajectoryAudit.cityCount, 13);
assert.equal(report.trajectoryAudit.scenarioCount, 4);
assert.equal(report.trajectoryAudit.yearCount, 76);
assert.equal(report.trajectoryAudit.resultCount, 52);
assert.ok(report.trajectoryAudit.trendReviewCount > 0);
assert.equal(report.observedBaselineAudit.version, "observed-baseline-audit-v1");
assert.equal(report.observedBaselineAudit.cityCount, 13);
assert.ok(report.observedBaselineAudit.maxTemperatureDifferenceC <= 0.02);
assert.ok(report.observedBaselineAudit.maxPrecipitationDifferenceMm <= 0.05);
assert.equal(report.validationReport.repoPath, "docs/VALIDATION_REPORT.md");
assert.equal(report.validationReport.historicalObservationHindcast, "pending");
assert.equal(report.validationReport.observedBaselineCrossCheck, "passed");
assert.ok(report.validationReport.blockers.some((blocker: string) => blocker.includes("No NOAA/ERA5/station")));
assert.ok(report.validationReport.trendReviewSummary.some((item: any) => item.kind === "precipStep" && item.count >= 1));
assert.ok(report.executableChecks.includes("npm run smoke:node-performance"));
assert.ok(report.limitations.some((limit: string) => limit.includes("Replit deployment")));
assert.ok(report.limitations.some((limit: string) => limit.includes("Natural Earth populated places")));
assert.ok(report.limitations.some((limit: string) => limit.includes("quantified AMOC")));

const dataQualityPage = fs.readFileSync("client/src/pages/data-quality.tsx", "utf-8");
assert.ok(dataQualityPage.includes("Source and license registry"));
assert.ok(dataQualityPage.includes("No registry row means no public metric"));
assert.ok(dataQualityPage.includes("Commercial:"));
assert.ok(dataQualityPage.includes("Redistribution:"));

console.log("data-quality smoke passed");
