import assert from "node:assert/strict";
import fs from "node:fs";
import { loadDataQuality } from "../server/data-quality";

const report = loadDataQuality() as Record<string, any>;

assert.equal(report.version, "data-quality-v1");
assert.ok(String(report.methodVersion).startsWith("grounded-grid-i16-v3"));
assert.equal(report.sourceRegistryVersion, "source-registry-v1");
assert.ok(Array.isArray(report.artifacts) && report.artifacts.length >= 10);
assert.ok(report.artifacts.every((artifact: any) => artifact.bytes > 0 && /^[a-f0-9]{64}$/.test(artifact.sha256)));
assert.ok(report.sourceRegistry.rowCount >= 15);
assert.ok(report.sourceRegistry.rows.some((row: any) => row.sourceId === "stull-2011-wetbulb-approximation" && row.displayPolicy === "show-as-derived-screening-context-not-advice"));
assert.ok(report.sourceRegistry.rows.some((row: any) => row.sourceId === "ipcc-ar6-amoc" && row.displayPolicy === "show-as-context-no-local-correction"));
assert.ok(report.sourceRegistry.rows.some((row: any) => row.sourceId === "natural-earth-coastline-110m-v5" && row.displayPolicy === "show-with-coastal-proximity-caveat"));
assert.ok(report.sourceRegistry.rows.some((row: any) => row.sourceId === "natural-earth-populated-places-110m-v5" && row.displayPolicy === "show-with-bounded-catalog-caveat"));
assert.ok(report.sourceRegistry.rows.some((row: any) => row.sourceId === "natural-earth-country-population-weighted-v1" && row.displayPolicy === "show-with-country-aggregate-caveat"));
assert.ok(report.sourceRegistry.rows.some((row: any) => row.sourceId === "nasa-power-meteorology-monthly-v10" && row.displayPolicy === "show-as-validation-source-not-forecast-correction"));
assert.ok(report.sourceRegistry.rows.some((row: any) => row.sourceId === "unep-egr-2025-current-policies" && row.displayPolicy === "show-as-policy-context-no-local-correction"));
assert.ok(report.sourceRegistry.rows.some((row: any) => row.sourceId === "cat-2025-warming-projections" && row.displayPolicy === "show-as-policy-context-no-local-correction"));
assert.ok(String(report.sourceRegistry.policy).includes("No public metric"));
const cmip6Source = report.sourceRegistry.rows.find((row: any) => row.sourceId === "cmip6-scenariomip");
assert.ok(cmip6Source);
assert.ok(String(cmip6Source.license).includes("Model-specific CMIP6 terms"));
assert.ok(String(cmip6Source.method).includes("Raw model-consensus anomaly"));
assert.ok(Array.isArray(cmip6Source.variables) && cmip6Source.variables.includes("temperature anomaly"));
assert.ok(Array.isArray(cmip6Source.variables) && cmip6Source.variables.includes("relative humidity anomaly"));
const wetBulbSource = report.sourceRegistry.rows.find((row: any) => row.sourceId === "stull-2011-wetbulb-approximation");
assert.equal(wetBulbSource?.commercialReuse, "review-required");
assert.ok(String(wetBulbSource?.method).includes("humid-heat screening context"));
const etccdiSource = report.sourceRegistry.rows.find((row: any) => row.sourceId === "cmip6-etccdi");
assert.equal(etccdiSource?.commercialReuse, "restricted");
assert.equal(etccdiSource?.redistribution, "restricted");
const naturalEarthSource = report.sourceRegistry.rows.find((row: any) => row.sourceId === "natural-earth-populated-places-110m-v5");
assert.equal(naturalEarthSource?.commercialReuse, "allowed");
assert.ok(String(naturalEarthSource?.license).includes("public domain"));
const nasaPowerSource = report.sourceRegistry.rows.find((row: any) => row.sourceId === "nasa-power-meteorology-monthly-v10");
assert.equal(nasaPowerSource?.commercialReuse, "allowed-with-attribution");
assert.ok(String(nasaPowerSource?.method).includes("external observed-climatology validation"));
assert.ok(String(nasaPowerSource?.method).includes("No forecast values are corrected"));
const coastlineSource = report.sourceRegistry.rows.find((row: any) => row.sourceId === "natural-earth-coastline-110m-v5");
assert.equal(coastlineSource?.commercialReuse, "allowed");
assert.ok(String(coastlineSource?.method).includes("coarse coastal-relevance flag"));
const countryAggregateSource = report.sourceRegistry.rows.find((row: any) => row.sourceId === "natural-earth-country-population-weighted-v1");
assert.equal(countryAggregateSource?.commercialReuse, "allowed");
assert.ok(String(countryAggregateSource?.method).includes("weighted across included points"));
assert.equal(report.defaultScenarioPolicy.scenario, "ssp245");
assert.equal(report.defaultScenarioPolicy.policyVersion, "current-policy-reference-2025");
assert.ok(report.defaultScenarioPolicy.basis.includes("UNEP current-policy"));
assert.ok(report.defaultScenarioPolicy.basis.includes("not a prediction or hidden scenario average"));
assert.deepEqual(report.defaultScenarioPolicy.sourceIds, ["unep-egr-2025-current-policies", "cat-2025-warming-projections"]);
assert.deepEqual(report.defaultScenarioPolicy.supportedFullForecastScenarios, ["ssp126", "ssp245", "ssp370", "ssp585"]);
assert.equal(report.defaultScenarioPolicy.gridHash, report.grids.primary.artifactHash);
assert.ok(String(report.defaultScenarioPolicy.gridHash).startsWith("sha256:0dc3f9d188e4d757"));
assert.equal(report.rankings.catalogCount, 3);
assert.ok(report.rankings.catalogSize > 111);
assert.equal(report.rankings.entryCount, 2448);
assert.ok(report.rankings.catalogs.some((catalog: any) => catalog.catalog === "curated_cities" && catalog.catalogSize === 45));
assert.ok(report.rankings.catalogs.some((catalog: any) => catalog.catalog === "natural_earth_populated_places_110m" && catalog.catalogSize === 66));
assert.ok(report.rankings.catalogs.some((catalog: any) => catalog.catalog === "natural_earth_country_population_place_weighted" && catalog.catalogSize >= 25));
assert.ok(report.rankings.sourceIds.includes("natural-earth-populated-places-110m-v5"));
assert.ok(report.rankings.sourceIds.includes("natural-earth-country-population-weighted-v1"));
assert.equal(report.coastalProximity.catalog, "natural_earth_coastline_110m");
assert.equal(report.coastalProximity.sourceId, "natural-earth-coastline-110m-v5");
assert.equal(report.coastalProximity.thresholdsKm.coastal, 50);
assert.equal(report.coastalProximity.thresholdsKm.nearCoastal, 100);
assert.equal(report.coastalProximity.thresholdsKm.regional, 250);
assert.ok(report.coastalProximity.lineCount >= 100);
assert.ok(report.coastalProximity.pointCount >= 3000);
assert.ok(String(report.coastalProximity.method).includes("nearest distance"));
assert.ok(Array.isArray(report.enrichmentReadiness));
assert.ok(report.enrichmentReadiness.some((item: any) => item.key === "humid_heat" && item.status === "partial" && String(item.publicBehavior).includes("wet-bulb")));
assert.ok(report.enrichmentReadiness.some((item: any) => item.key === "freshwater" && item.status === "partial" && String(item.groundedBasis).includes("Aqueduct 4.0")));
assert.ok(report.enrichmentReadiness.some((item: any) => item.key === "freshwater" && String(item.publicBehavior).includes("water-stress")));
assert.ok(report.enrichmentReadiness.some((item: any) => item.key === "biodiversity" && item.status === "withheld"));
assert.ok(report.enrichmentReadiness.some((item: any) => item.key === "cold_season_context" && item.status === "partial" && String(item.publicBehavior).includes("monthly-mean freeze-month")));
assert.ok(report.enrichmentReadiness.some((item: any) => item.key === "cold_season_context" && String(item.groundedBasis).includes("ETCCDI") && String(item.groundedBasis).includes("NEX-GDDP")));
assert.ok(report.enrichmentReadiness.some((item: any) => item.key === "humid_heat" && String(item.groundedBasis).includes("Stull") && String(item.groundedBasis).includes("NEX-GDDP")));
assert.ok(report.enrichmentReadiness.some((item: any) => item.key === "infrastructure" && String(item.groundedBasis).includes("degree-day")));
assert.ok(report.sourceRegistry.rows.some((row: any) => row.sourceId === "nasa-nex-gddp-cmip6-v1" && row.license === "cc0-1.0" && row.commercialReuse === "public-domain"));
assert.ok(report.artifacts.some((artifact: any) => artifact.path === "data/nex-gddp.json"));
assert.ok(report.artifacts.some((artifact: any) => artifact.path === "data/nex-gddp.u16.gz"));
assert.equal(report.nexGddp.sourceId, "nasa-nex-gddp-cmip6-v1");
assert.equal(report.nexGddp.license, "cc0-1.0");
assert.equal(report.nexGddp.resolutionDegrees, 0.25);
assert.deepEqual(report.nexGddp.scenarios, ["ssp126", "ssp245", "ssp370", "ssp585"]);
assert.ok(report.nexGddp.attribution.includes("NEX-GDDP") && report.nexGddp.attribution.includes("Stull"));
assert.ok(report.artifacts.some((artifact: any) => artifact.path === "client/public/coastal-proximity.natural-earth-110m.json"));
assert.ok(report.artifacts.some((artifact: any) => artifact.path === "data/freshwater-stress.aqueduct40.json"));
assert.ok(report.artifacts.some((artifact: any) => artifact.path === "data/freshwater-stress.aqueduct40.u16.gz"));
assert.equal(report.freshwaterStress.sourceId, "wri-aqueduct-40-water-stress-v1");
assert.equal(report.freshwaterStress.license, "attribution");
assert.ok(String(report.freshwaterStress.attribution).includes("Aqueduct"));
assert.deepEqual(report.freshwaterStress.years, [2030, 2050, 2080]);
assert.ok(report.freshwaterStress.basinCount > 10000);
assert.equal(report.freshwaterStress.scenarioMap.ssp245, null);
assert.ok(report.freshwaterStress.caveats.some((caveat: string) => caveat.toLowerCase().includes("prioritization")));
assert.ok(report.sourceRegistry.rows.some((row: any) => row.sourceId === "wri-aqueduct-40-water-stress-v1" && row.displayPolicy === "show-with-subbasin-prioritization-caveat" && row.license === "attribution"));
assert.ok(report.limitations.some((limit: string) => limit.includes("WRI Aqueduct 4.0")));
assert.equal(report.trajectoryAudit.cityCount, 13);
assert.equal(report.trajectoryAudit.scenarioCount, 4);
assert.equal(report.trajectoryAudit.yearCount, 76);
assert.equal(report.trajectoryAudit.resultCount, 52);
assert.ok(report.trajectoryAudit.trendReviewCount > 0);
assert.equal(report.observedBaselineAudit.version, "observed-baseline-audit-v1");
assert.equal(report.observedBaselineAudit.cityCount, 13);
assert.ok(report.observedBaselineAudit.maxTemperatureDifferenceC <= 0.02);
assert.ok(report.observedBaselineAudit.maxPrecipitationDifferenceMm <= 0.05);
assert.equal(report.observedClimatologyValidation.version, "nasa-power-observed-climatology-validation-v1");
assert.equal(report.observedClimatologyValidation.status, "passed-with-caveats");
assert.equal(report.observedClimatologyValidation.cityCount, 13);
assert.deepEqual(report.observedClimatologyValidation.sourceIds, ["worldclim-v2-1", "nasa-power-meteorology-monthly-v10"]);
assert.equal(report.observedClimatologyValidation.period.start, 1981);
assert.equal(report.observedClimatologyValidation.period.end, 2000);
assert.ok(report.observedClimatologyValidation.summary.maxAbsTemperatureDifferenceC <= 2);
assert.ok(report.observedClimatologyValidation.caveats.some((caveat: string) => caveat.includes("does not validate future CMIP6 scenario trends")));
assert.equal(report.validationReport.repoPath, "docs/VALIDATION_REPORT.md");
assert.equal(report.validationReport.historicalObservationHindcast, "partial-present-climate-baseline-validation");
assert.equal(report.validationReport.observedBaselineCrossCheck, "passed");
assert.equal(report.validationReport.externalObservedClimatologyValidation, "passed-with-caveats");
assert.ok(report.validationReport.blockers.some((blocker: string) => blocker.includes("time-varying historical projection-vs-observation")));
assert.ok(report.validationReport.trendReviewSummary.some((item: any) => item.kind === "precipStep" && item.count >= 1));
assert.ok(report.executableChecks.includes("npm run smoke:node-performance"));
assert.ok(report.executableChecks.includes("npm run build:observation-validation"));
assert.ok(report.limitations.some((limit: string) => limit.includes("Replit deployment")));
assert.ok(report.limitations.some((limit: string) => limit.includes("Natural Earth populated places")));
assert.ok(report.limitations.some((limit: string) => limit.includes("Natural Earth 1:110m nearest-coast screen")));
assert.ok(report.limitations.some((limit: string) => limit.includes("NASA POWER observed-climatology validation")));
assert.ok(report.limitations.some((limit: string) => limit.includes("quantified AMOC")));

const dataQualityPage = fs.readFileSync("client/src/pages/data-quality.tsx", "utf-8");
assert.ok(dataQualityPage.includes("Source and license registry"));
assert.ok(dataQualityPage.includes("NASA POWER"));
assert.ok(dataQualityPage.includes("Coastal relevance screen"));
assert.ok(dataQualityPage.includes("Freshwater availability screen"));
assert.ok(dataQualityPage.includes("Enrichment readiness ledger"));
assert.ok(dataQualityPage.includes("withheld rows stay out"));
assert.ok(dataQualityPage.includes("not a parcel exposure or flood model"));
assert.ok(dataQualityPage.includes("No registry row means no public metric"));
assert.ok(dataQualityPage.includes("Commercial:"));
assert.ok(dataQualityPage.includes("Redistribution:"));

console.log("data-quality smoke passed");
